/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package escola.conexao;

import DAO.AlunoDAO;
import DAO.ProfessorDAO;
import beans.Aluno;
import beans.Professor;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author iagov
 */
public class EscolaEditar extends javax.swing.JFrame {

    /**
     * Creates new form EscolaEditar
     */
    public EscolaEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        btnConsultar = new javax.swing.JButton();
        txtIdAluno = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblIdATTAluno = new javax.swing.JLabel();
        txtIDAluno = new javax.swing.JTextField();
        txtIDATTAluno = new javax.swing.JTextField();
        txtNomeAluno = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblAlunos = new javax.swing.JLabel();
        rdoAluno = new javax.swing.JRadioButton();
        lblProf = new javax.swing.JLabel();
        rdoProf = new javax.swing.JRadioButton();
        txtId1 = new javax.swing.JLabel();
        txtIDProf = new javax.swing.JTextField();
        lblIdATT1 = new javax.swing.JLabel();
        txtIDATTProf = new javax.swing.JTextField();
        lblNomeProf = new javax.swing.JLabel();
        txtNomeProf = new javax.swing.JTextField();
        lblIdadeAluno = new javax.swing.JLabel();
        txtIdadeAluno = new javax.swing.JTextField();
        lblCursoAluno = new javax.swing.JLabel();
        txtCursoAluno = new javax.swing.JTextField();
        lblIdadeProf = new javax.swing.JLabel();
        txtIdadeProf = new javax.swing.JTextField();
        lblCursoProf = new javax.swing.JLabel();
        txtCursoProf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtIdAluno.setText("ID:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitulo.setText("Editar e Excluir Pessoas:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lblIdATTAluno.setText("ID:");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        lblAlunos.setText("Alunos:");

        btgTipo.add(rdoAluno);

        lblProf.setText("Professor:");

        btgTipo.add(rdoProf);

        txtId1.setText("ID:");

        lblIdATT1.setText("ID:");

        lblNomeProf.setText("Nome:");

        txtNomeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProfActionPerformed(evt);
            }
        });

        lblIdadeAluno.setText("Idade:");

        lblCursoAluno.setText("Curso:");

        lblIdadeProf.setText("Idade:");

        lblCursoProf.setText("Curso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtIdAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAlunos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoAluno))
                                    .addComponent(txtIDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoProf)
                                        .addGap(59, 59, 59))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIDProf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCursoAluno)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblIdadeAluno)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblIdATTAluno)
                                                .addComponent(lblNome))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNomeAluno)
                                                .addComponent(txtIDATTAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtCursoAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIdATT1)
                                            .addComponent(lblNomeProf))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNomeProf)
                                            .addComponent(txtIDATTProf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCursoProf, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIdadeProf, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIdadeProf)
                                            .addComponent(txtCursoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(110, 110, 110))))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAlunos)
                        .addComponent(rdoAluno))
                    .addComponent(rdoProf)
                    .addComponent(lblProf))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAluno)
                    .addComponent(txtIDAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId1)
                    .addComponent(txtIDProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdATTAluno)
                    .addComponent(txtIDATTAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdATT1)
                    .addComponent(txtIDATTProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdadeAluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCursoAluno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdadeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdadeProf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCursoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCursoProf))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limparFormulario(){
           txtNomeAluno.setText("");
           txtNomeProf.setText("");
           txtIDATTAluno.setText("");
           txtIDATTProf.setText("");
           txtCursoAluno.setText("");
           txtIDAluno.setText("");
           txtIDProf.setText("");
           txtIdadeAluno.setText("");
           txtIdadeProf.setText("");
           txtCursoProf.setText("");
           
       }
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        
        if (rdoAluno.isSelected()){
        int idAluno = Integer.parseInt(txtIDAluno.getText());
        AlunoDAO aDAO = new AlunoDAO();
        Aluno a = aDAO.getAluno(idAluno);
        if(a == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Pessoa não encontrada!");
        }
        else{
            limparFormulario();
            txtIDATTAluno.setText(String.valueOf(a.getId_aluno()));
            txtNomeAluno.setText(a.getNome());
            txtIdadeAluno.setText(String.valueOf(a.getIdade()));
            txtCursoAluno.setText(a.getCurso());
        }
        }
        else {
            int idProfessor = Integer.parseInt(txtIDProf.getText());
            ProfessorDAO pDAO = new ProfessorDAO();
            Professor p = pDAO.getProfessor (idProfessor);
            
            if(p == null){
                limparFormulario();
                JOptionPane.showMessageDialog (this, "Pessoa não encontrada!");
            }
            else {
                limparFormulario();
                txtIDATTProf.setText(String.valueOf(p.getId_professor()));
                txtNomeProf.setText(p.getNome());
                txtIdadeProf.setText(String.valueOf(p.getIdade()));
                txtCursoProf.setText(p.getDisciplina());
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if(rdoProf.isSelected()){
            Professor p = new Professor();
            p.setNome(txtNomeProf.getText());
            p.setIdade(Integer.parseInt(txtIdadeProf.getText()));
            p.setDisciplina(txtCursoProf.getText());
            p.setId_professor(Integer.parseInt(txtIDATTProf.getText()));
            
            ProfessorDAO pDAO = new ProfessorDAO();
            pDAO.editar(p);
            limparFormulario();
        }
        else {
            Aluno a = new Aluno();
            a.setNome(txtNomeAluno.getText());
            a.setIdade(Integer.parseInt(txtIdadeAluno.getText()));
            a.setCurso(txtCursoAluno.getText());
            a.setId_aluno(Integer.parseInt(txtIDATTAluno.getText()));
            
            AlunoDAO aDAO = new AlunoDAO();
            aDAO.editar(a);
            limparFormulario();
        }
        
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo cancelar?", "Exclusão", JOptionPane.YES_NO_OPTION);
        if (rdoProf.isSelected() || resposta == JOptionPane.YES_OPTION){
            ProfessorDAO pDAO = new ProfessorDAO();
            pDAO.excluir(Integer.parseInt(txtIDProf.getText()));
            limparFormulario();
        }
        else{
            if(rdoAluno.isSelected() || resposta == JOptionPane.YES_OPTION){
                AlunoDAO aDAO = new AlunoDAO();
                aDAO.excluir(Integer.parseInt(txtIDAluno.getText()));
                limparFormulario();
            }
        }
       
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolaEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblCursoAluno;
    private javax.swing.JLabel lblCursoProf;
    private javax.swing.JLabel lblIdATT1;
    private javax.swing.JLabel lblIdATTAluno;
    private javax.swing.JLabel lblIdadeAluno;
    private javax.swing.JLabel lblIdadeProf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeProf;
    private javax.swing.JLabel lblProf;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdoAluno;
    private javax.swing.JRadioButton rdoProf;
    private javax.swing.JTextField txtCursoAluno;
    private javax.swing.JTextField txtCursoProf;
    private javax.swing.JTextField txtIDATTAluno;
    private javax.swing.JTextField txtIDATTProf;
    private javax.swing.JTextField txtIDAluno;
    private javax.swing.JTextField txtIDProf;
    private javax.swing.JLabel txtId1;
    private javax.swing.JLabel txtIdAluno;
    private javax.swing.JTextField txtIdadeAluno;
    private javax.swing.JTextField txtIdadeProf;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeProf;
    // End of variables declaration//GEN-END:variables
}
