/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mercado.conexao;

import DAO.CategoriaDAO;
import DAO.ProdutoDAO;
import beans.Categoria;
import beans.Produto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iagov
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        setSize(450, 400);
        setLocationRelativeTo(null);
        carregarProdutos();
        preencherComboCategorias();
    }
    
    public void carregarProdutos() {
    ProdutoDAO produtoDAO = new ProdutoDAO();
    List<Produto> produtos = produtoDAO.listarProdutosComCategoria();
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nome");
    model.addColumn("Preço");
    model.addColumn("Quantidade");
    model.addColumn("Categoria");

    for (Produto produto : produtos) {
        model.addRow(new Object[] {
            produto.getId(),
            produto.getNome(),
            produto.getPreco(),
            produto.getQuantidade(),
            produto.getNomeCategoria()
        });
    }

    tblRelatorio.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        lblBusca = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        lblBusca1 = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox();
        btnFiltrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRelatorio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 65, 463, 350);

        lblBusca.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblBusca.setText("Categorias:");
        getContentPane().add(lblBusca);
        lblBusca.setBounds(10, 40, 83, 20);

        btnBuscar1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1);
        btnBuscar1.setBounds(250, 10, 80, 26);

        lblBusca1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblBusca1.setText("Busca Prod:");
        getContentPane().add(lblBusca1);
        lblBusca1.setBounds(6, 6, 86, 20);

        txtBuscar1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        getContentPane().add(txtBuscar1);
        txtBuscar1.setBounds(100, 10, 128, 25);

        getContentPane().add(cmbCategoria);
        cmbCategoria.setBounds(100, 40, 130, 22);

        btnFiltrar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        getContentPane().add(btnFiltrar);
        btnFiltrar.setBounds(250, 40, 80, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mercado.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void preencherComboCategorias() {
    CategoriaDAO categoriaDAO = new CategoriaDAO();
    List<Categoria> categorias = categoriaDAO.getCategorias();
    cmbCategoria.removeAllItems();
    cmbCategoria.addItem(new Categoria(0, "Todas"));

    for (Categoria categoria : categorias) {
        cmbCategoria.addItem(categoria); 
    }
}
    public void filtrarPorCategoria() {
    Categoria categoriaSelecionada = (Categoria) cmbCategoria.getSelectedItem();
    int categoriaId = categoriaSelecionada.getId_cat(); 

    ProdutoDAO produtoDAO = new ProdutoDAO();
    List<Produto> produtos;

    if (categoriaId == 0) { 
        produtos = produtoDAO.listarProdutosComCategoria();
    } else {
        produtos = produtoDAO.filtrarProdutosPorCategoria(categoriaId);
    }

   
    DefaultTableModel model = (DefaultTableModel) tblRelatorio.getModel();
    model.setRowCount(0);

    
    for (Produto produto : produtos) {
        model.addRow(new Object[]{
            produto.getId(),
            produto.getNome(),
            produto.getPreco(),
            produto.getQuantidade(),
            produto.getNomeCategoria()
        });
    }
}

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
         String nomeBusca = txtBuscar1.getText(); // Obtem o texto do campo de busca
        ProdutoDAO produtoDAO = new ProdutoDAO();
        List<Produto> produtos = produtoDAO.buscarProdutoPorNome(nomeBusca);

        DefaultTableModel model = (DefaultTableModel) tblRelatorio.getModel();
        model.setRowCount(0);

        for (Produto produto : produtos) {
            model.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getPreco(),
                produto.getQuantidade(),
                produto.getNomeCategoria()
            });
    }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblBusca1;
    private javax.swing.JTable tblRelatorio;
    private javax.swing.JTextField txtBuscar1;
    // End of variables declaration//GEN-END:variables
}
